-- Neovim config
require "user.options"
require "user.remap"
require "user.packer"
require "user.colors"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.bufferline"
